### ISSUE TITLE
Game crashes when equipping potato seed/any other food seed

### ISSUE THREAD

**Issue by hammyexe** [IntelSDM/RustDMACheat#12]
My game crashes whenever I hold any of these items, sometimes its a delayed crash. I suspect its due to the recoil setting because it outputs the same as if I would be holding a weapon.

**Comment by arlohewitt** [comment]
yeah ill second this.

Also, im having issues with the adminflag now that its written to once as a cvar, im pretty sure the server i am on sends a command to each client every now and then that sets the admin flag back to false. It was working fine before the workbech fix, but i am noticing i no longer have the flag after a minute or so from program startup.
Im guessing this could be solved by setting it as a cvar, then reading it in the mainthread() and setting it back to true if it becomes false, this should also not cause any workbench issues either since you are not writing to it 24/7.

**Comment by IntelSDM** [comment]
On the weekend I will add a periodical update for admin flag. I thought I fixed the seed crash but and tried to replicate it before I pushed the last update. I will also try and fix that on the weekend.
