### ISSUE TITLE
Admin Flags Detected

### ISSUE THREAD

**Issue by Rakeshmonkee** [IntelSDM/RustDmaCheat#70]
Just want to point out that enabling admin flags and Admin ESP is a detected feature and is not viable since server admins can see who has Admin permissions. I have tested this on Facepunch servers and have been banned due to it.

**Comment by arlohewitt** [comment]
Admin flag is detectable on some servers, the server owner sends a package of commands all at once and the resulting packet sent back to the server lets them know that your client illegally blocked 'noclip'.

Admin ESP doesnt set the admin flag so its not detected whatsoever.

If you still want to use freecam without writing to adminflag, find your localplayers BasePlayer class :

`public PlayerEyes eyes; // 0xA90` - this points you to your instance of PlayerEyes.

`public static readonly Vector3 EyeOffset; // 0x0` - you can then write to the EyeOffset Vector3 in order to move your camera around as you please, obviously you would also want to factor in rotation and whatnot.

Careful when accessing that vector, you need to access the static fields, the chain would be :

`PlayerEyes + 0x0] 0xB8] 0x0] = Vec 3 EyeOffset`

if you want to take this a step further, you can disable game inputs utilising the static "Facepunch.Input_TypeInfo" and writing  the 'isPressed' bool to true for keys you want disable temporarliy. This prevents your character moving while you are in this debug camera mode, but still alows the DMA card to read inputs and write to your EyeOffset accordingly.

**Comment by Rcazp** [comment]
please answer does the cheat work now?

**Comment by Rakeshmonkee** [comment]
> please answer does the cheat work now?

no

**Comment by arlohewitt** [comment]
Not currently, the devs have begun encrypting il2cpp strings with SHA1 as of yesterday + there is a new wrapper class which sits in between statics and a lot of the information that the cheat is set up to read.

The wrapper is being reversed on UC and i will update the cheat as soon as i figure out the changes that they have made.

On top of that, i have replaced AdminFlag with an external debug camera method which will prevent people from being banned for it. I will create a branch on my fork when i update properly for this rather than pushing it to main, since people may still want adminflag.

**Comment by Rcazp** [comment]
Thanks for the answer.

**Comment by Rakeshmonkee** [comment]
> Not currently, the devs have begun encrypting il2cpp strings with SHA1 as of yesterday + there is a new wrapper class which sits in between statics and a lot of the information that the cheat is set up to read.
> 
> The wrapper is being reversed on UC and i will update the cheat as soon as i figure out the changes that they have made.
> 
> On top of that, i have replaced AdminFlag with an external debug camera method which will prevent people from being banned for it. I will create a branch on my fork when i update properly for this rather than pushing it to main, since people may still want adminflag.

W job replacing addmin flag with debug camera
