### ISSUE TITLE
Releases tab not showing on any of your projects.

### ISSUE THREAD

**Issue by rushinz** [IntelSDM/RustDmaCheat#72]
Hey i'm not sure why but other github projects show their releases just fine, but yours don't come up.

**Comment by sdmaxINC** [comment]
> Hey i'm not sure why but other github projects show their releases just fine, but yours don't come up.

what other github projects?

**Comment by arlohewitt** [comment]
This project has no Release tab because a release has never been uploaded.
I would always advise compiling everything from source, as it allows you to ensure nothing mallicious is hidden in an executable.

On top of that, this is discontinued as of the rust encryption update, though there is good info which may help you update it yourself in another issue named "Obfuscation Wrapper"
