### ISSUE TITLE
Help With Scatter Reads

### ISSUE THREAD

**Issue by ConnorMAD** [IntelSDM/RustDmaCheat#8]
Hi, I'm learning to program now, I saw that you use scatter, I couldn't identify how you read several address strings with scatter to make it quick?

type:
read A = 0x500
and in the same function read B = A + 0x600

**Comment by IntelSDM** [comment]
So what you're doing is impossible, picture it like this: 
So you are sending off a package of reads, This package of reads has 2 addresses
a = Class + 0x10
b = (a) + 0x50
Once it gets the bundle of reads it just says, DO IT and sends all the reads at once but returns them all at the same time too not one by one. So the variable A is set at the same time a B so when you packaged up the data to the card it just got A = Class + 0x10 and B = 0+0x10 as A doesn't have a value yet.

If you want to use scatter reads then you must loop your entities multiple times and read each part individually, so i loop over players in my player caching to get the address, then I loop again read to get the base projectile class and player model, Then i loop over it again and get the position.  So I use 3 loops but I am getting all the entities addresses at the same time and then reloop using those addresses so i can get all of the playemodels at the same time. Therefore instead of packaging all the reads for 1 player at once, we use it to package 1 or 2 reads for all players at once. 

Here is my code example for caching the player list:
```cpp
	if (VisiblePlayerList == 0)
		return;
	std::vector< std::shared_ptr<BasePlayer>> templayerlist;
	uint32_t size = TargetProcess.Read<uint32_t>(VisiblePlayerList + VisiblePlayerListSize);
	uint64_t buffer = TargetProcess.Read<uint64_t>(VisiblePlayerList + VisiblePlayerListBuffer);
	if(size == 0 || buffer == 0)
		return;
	std::vector<uint64_t> playerlist;
	playerlist.resize(size);
	auto handle = TargetProcess.CreateScatterHandle(); // create bundle
	for (int i = 0; i < size; i++)
	{
		TargetProcess.QueueScatterReadEx(handle, buffer + (0x20 + (i * 8)), reinterpret_cast<void*>(&playerlist[i]), sizeof(uint64_t)); // get all the addresses
	
	}
	TargetProcess.ExecuteScatterRead(handle); // execute the bundle
	TargetProcess.CloseScatterHandle(handle);
	handle = TargetProcess.CreateScatterHandle(); // new bundle
	for (int i = 0; i < size; i++)
	{
		if (playerlist[i] == NULL)
			continue;
		templayerlist.push_back(std::make_shared<BasePlayer>(playerlist[i], handle)); // create into class, this will intiailize a scatter read in the class constructor
	
	}
	TargetProcess.ExecuteScatterRead(handle); // execute the bundle
	TargetProcess.CloseScatterHandle(handle);
	handle = TargetProcess.CreateScatterHandle(); // new bundle 
	for (int i = 0; i < templayerlist.size(); i++)
	{
		std::shared_ptr<BasePlayer> player = templayerlist[i];
		player->IntializeClasses(handle); // this contains a scatter read for the player model class
	}
	TargetProcess.ExecuteScatterRead(handle); // execute the bundle
	TargetProcess.CloseScatterHandle(handle);
	handle = TargetProcess.CreateScatterHandle(); // new scatter read
	for (int i = 0; i < templayerlist.size(); i++)
	{
		std::shared_ptr<BasePlayer> player = templayerlist[i];
		player->SetName(handle); // read the name
		player->SetNPC(handle); // read if its an npc
	}
	TargetProcess.ExecuteScatterRead(handle); // execute the bundle
	TargetProcess.CloseScatterHandle(handle);
	PlayerList = templayerlist;
```

As you can see I go step by step scatter reading the player's information so I never use an address that's going to rely on an address that I don't already have, if I need an address for a read then I read it all in 1 bundle, make a new loop and read what i need from there. Just keep making loops for each layer of information you need down the classes.

**Comment by matheusbranhan** [comment]
Thank you for such a complete answer.
I have another doubt, I have another doubt, i looked you eftrecode, How do you access the offsets?

**Comment by IntelSDM** [comment]
> Is this only possible in C#? or is it possible in python too?

Sure, You can access mono types and fields in python externally, You need to adapt one of these sources to use python:
https://github.com/reahly/mono-external-lib
https://github.com/imerzan/MonoSharp
